### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by SahaAbhirupa** [DeanHazineh/DFlat-pytorch#1]
the setup is failing with the following error:

```bash
error: numpy 2.0.0rc1 is installed but numpy<2,>=1.26.0 is required by {'pandas'}
```

 Can you tell me which python version you have used?

**Comment by harikantbajaj** [comment]
I'm Using Python-3.0.8 
Check Your Python Version:
 `python --version OR python3 --version`

**Comment by DeanHazineh** [comment]
The package was tested and developed on version > 3.9 but it should work on any version > 3.6. There is now a PyPI install.

**Comment by SahaAbhirupa** [comment]
Dear Dean,

Thanks for the reply, I could get that running.


Best regards,
Abhirupa
________________________________
